// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPSID
{
        public const string achievement_finish_level_4_with_all_stars = "CgkIz4CsybwSEAIQBQ"; // <GPGSID>
        public const string achievement_finish_level_2_with_all_stars = "CgkIz4CsybwSEAIQAw"; // <GPGSID>
        public const string achievement_finish_level_8_with_all_stars = "CgkIz4CsybwSEAIQCQ"; // <GPGSID>
        public const string achievement_finish_level_13_with_all_stars = "CgkIz4CsybwSEAIQDg"; // <GPGSID>
        public const string achievement_finish_level_10_with_all_stars = "CgkIz4CsybwSEAIQCw"; // <GPGSID>
        public const string achievement_finish_level_11_with_all_stars = "CgkIz4CsybwSEAIQDA"; // <GPGSID>
        public const string achievement_finish_level_5_with_all_stars = "CgkIz4CsybwSEAIQBg"; // <GPGSID>
        public const string achievement_finish_level_9_with_all_stars = "CgkIz4CsybwSEAIQCg"; // <GPGSID>
        public const string achievement_finish_level_12_with_all_stars = "CgkIz4CsybwSEAIQDQ"; // <GPGSID>
        public const string achievement_finish_level_6_with_all_stars = "CgkIz4CsybwSEAIQBw"; // <GPGSID>
        public const string achievement_finish_level_3_with_all_stars = "CgkIz4CsybwSEAIQBA"; // <GPGSID>
        public const string achievement_finish_the_tutorial = "CgkIz4CsybwSEAIQAg"; // <GPGSID>
        public const string achievement_finish_level_15_with_all_stars = "CgkIz4CsybwSEAIQEA"; // <GPGSID>
        public const string achievement_finish_level_7_with_all_stars = "CgkIz4CsybwSEAIQCA"; // <GPGSID>
        public const string achievement_finish_level_14_with_all_stars = "CgkIz4CsybwSEAIQDw"; // <GPGSID>

}

